create table TBL_DEPARTMENT
(
    ID_DEPT   NUMBER generated as identity
        constraint TBL_DEPARTMENT_PK
            primary key,
    NAME_DEPT VARCHAR2(100)
)
/

INSERT INTO WAHYU.TBL_DEPARTMENT (ID_DEPT, NAME_DEPT) VALUES (1, 'IT');
INSERT INTO WAHYU.TBL_DEPARTMENT (ID_DEPT, NAME_DEPT) VALUES (2, 'Programmer');
INSERT INTO WAHYU.TBL_DEPARTMENT (ID_DEPT, NAME_DEPT) VALUES (21, 'Operational');
INSERT INTO WAHYU.TBL_DEPARTMENT (ID_DEPT, NAME_DEPT) VALUES (22, 'Administrator');
INSERT INTO WAHYU.TBL_DEPARTMENT (ID_DEPT, NAME_DEPT) VALUES (7, 'Finance');